GBIF.org (20 March 2026) GBIF Occurrence Download https://doi.org/10.15468/dl.cx2gyy

Animalia/Chordata/Mammalia/Primates/Callintrichidae

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("callintrichidae_raw.csv", sep="\t")
df.shape

(8412, 50)

In [13]:
df.columns

Index(['gbifID', 'datasetKey', 'occurrenceID', 'kingdom', 'phylum', 'class',
       'order', 'family', 'genus', 'species', 'infraspecificEpithet',
       'taxonRank', 'scientificName', 'verbatimScientificName',
       'verbatimScientificNameAuthorship', 'countryCode', 'locality',
       'stateProvince', 'occurrenceStatus', 'individualCount',
       'publishingOrgKey', 'decimalLatitude', 'decimalLongitude',
       'coordinateUncertaintyInMeters', 'coordinatePrecision', 'elevation',
       'elevationAccuracy', 'depth', 'depthAccuracy', 'eventDate', 'day',
       'month', 'year', 'taxonKey', 'speciesKey', 'basisOfRecord',
       'institutionCode', 'collectionCode', 'catalogNumber', 'recordNumber',
       'identifiedBy', 'dateIdentified', 'license', 'rightsHolder',
       'recordedBy', 'typeStatus', 'establishmentMeans', 'lastInterpreted',
       'mediaType', 'issue'],
      dtype='str')

In [14]:
df = df.loc[:, ["genus", "species", "stateProvince", "decimalLatitude", "decimalLongitude", "coordinateUncertaintyInMeters", "eventDate", "month", "year"]]
df.head()

,genus,species,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate,month,year
0,Callithrix,Callithrix aurita,São Paulo,-23.032046,-46.375152,30217.0,2014-04-20,4,2014
1,Callithrix,Callithrix jacchus,Piauí,-8.868018,-42.558185,NaN,2012-01-15T09:29:54,1,2012
2,Saguinus,Saguinus bicolor,Amazonas,-3.015908,-60.044437,10000.0,2012-05-27T09:10,5,2012
3,Mico,Mico melanurus,Mato Grosso,-16.222323,-56.206741,NaN,2009-09-10,9,2009
4,Callithrix,Callithrix jacchus,Rio de Janeiro,-22.975337,-43.230858,NaN,2009-08-19,8,2009

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8412 entries, 0 to 8411
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   genus                          8410 non-null   str
 1   species                        8237 non-null   str
 2   stateProvince                  8244 non-null   str
 3   decimalLatitude                8412 non-null   float64
 4   decimalLongitude               8412 non-null   float64
 5   coordinateUncertaintyInMeters  7022 non-null   float64
 6   eventDate                      8412 non-null   str
 7   month                          8412 non-null   int64
 8   year                           8412 non-null   int64
dtypes: float64(3), int64(2), str(4)
memory usage: 591.6 KB

In [16]:
df[df.isna().any(axis=1)]

,genus,species,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate,month,year
1,Callithrix,Callithrix jacchus,Piauí,-8.868018,-42.558185,NaN,2012-01-15T09:29:54,1,2012
3,Mico,Mico melanurus,Mato Grosso,-16.222323,-56.206741,NaN,2009-09-10,9,2009
4,Callithrix,Callithrix jacchus,Rio de Janeiro,-22.975337,-43.230858,NaN,2009-08-19,8,2009
5,Leontopithecus,Leontopithecus caissara,NaN,-25.255100,-48.066900,NaN,2025-12-20,12,2025
6,Mico,Mico emiliae,NaN,-9.590400,-55.933200,NaN,2019-11-22,11,2019
...,...,...,...,...,...,...,...,...,...
8406,Callithrix,Callithrix jacchus,Rio de Janeiro,-23.180730,-44.193430,NaN,2012-10-08,10,2012
8407,Callithrix,Callithrix jacchus,Rio de Janeiro,-23.186750,-44.199710,NaN,2012-10-06,10,2012
8408,Callithrix,Callithrix jacchus,Rio de Janeiro,-23.190830,-44.207710,NaN,2012-10-06,10,2012
8409,Mico,Mico melanurus,Mato Grosso,-16.330139,-57.807861,NaN,2014-07-20,7,2014
8410,Mico,Mico melanurus,Mato Grosso,-16.330167,-57.807833,NaN,2014-07-20,7,2014

In [17]:
df.fillna(
    {"species": "Unknown",
     "stateProvince": "Unknown",
     "coordinateUncertaintyInMeters": "Unknown"},
     inplace=True
)
df.dropna(inplace=True)
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [genus, species, stateProvince, decimalLatitude, decimalLongitude, coordinateUncertaintyInMeters, eventDate, month, year]
Index: []

In [18]:
df.value_counts("stateProvince")

stateProvince
São Paulo              1631
Rio de Janeiro         1359
Minas Gerais            810
Bahia                   658
Distrito Federal        499
Espírito Santo          418
Acre                    303
Mato Grosso             283
Pernambuco              279
Amazonas                263
Rio Grande do Norte     253
Ceará                   227
Santa Catarina          205
Paraíba                 172
Unknown                 168
Alagoas                 163
Pará                    155
Paraná                  141
Goiás                   116
Roraima                  89
Rondônia                 73
Sergipe                  52
Piauí                    29
Maranhão                 20
Mato Grosso do Sul       18
Tocantins                 9
Amapá                     9
Espirito Santo            4
Rio Grande do Sul         2
Rio Preto da Eva          1
Goias                     1
Name: count, dtype: int64

In [19]:
df["stateProvince"] = df["stateProvince"].replace("Goias", "Goiás")
df["stateProvince"] = df["stateProvince"].replace("Espirito Santo", "Espírito Santo")
df = df[df["stateProvince"] != "Rio Preto da Eva"]
df = df[df["year"] != 2026]

In [20]:
df.value_counts("stateProvince")

stateProvince
São Paulo              1602
Rio de Janeiro         1339
Minas Gerais            800
Bahia                   635
Distrito Federal        494
Espírito Santo          412
Acre                    301
Mato Grosso             282
Pernambuco              272
Amazonas                259
Rio Grande do Norte     243
Ceará                   216
Santa Catarina          204
Paraíba                 167
Unknown                 160
Alagoas                 155
Pará                    154
Paraná                  140
Goiás                   116
Roraima                  89
Rondônia                 72
Sergipe                  52
Piauí                    27
Maranhão                 19
Mato Grosso do Sul       18
Tocantins                 9
Amapá                     9
Rio Grande do Sul         2
Name: count, dtype: int64

In [21]:
df.to_csv("callintrichidae_clean.csv")