In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("penguins.csv")
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [6]:
df.dropna(inplace=True)
print(df["species"].value_counts())

species
Adelie       146
Gentoo       119
Chinstrap     68
Name: count, dtype: int64

In [7]:
df.to_csv("processed_penguins.csv")

In [26]:
print(df.columns)

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='str')

In [61]:
print(df.describe())

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      333.000000     333.000000         333.000000   333.000000
mean        43.992793      17.164865         200.966967  4207.057057
std          5.468668       1.969235          14.015765   805.215802
min         32.100000      13.100000         172.000000  2700.000000
25%         39.500000      15.600000         190.000000  3550.000000
50%         44.500000      17.300000         197.000000  4050.000000
75%         48.600000      18.700000         213.000000  4775.000000
max         59.600000      21.500000         231.000000  6300.000000

              year
count   333.000000
mean   2008.042042
std       0.812944
min    2007.000000
25%    2007.000000
50%    2008.000000
75%    2009.000000
max    2009.000000

In [62]:
df[["bill_depth_mm", "body_mass_g"]]

     bill_depth_mm  body_mass_g
0             18.7       3750.0
1             17.4       3800.0
2             18.0       3250.0
4             19.3       3450.0
5             20.6       3650.0
..             ...          ...
339           19.8       4000.0
340           18.1       3400.0
341           18.2       3775.0
342           19.0       4100.0
343           18.7       3775.0

[333 rows x 2 columns]

In [57]:
df.loc[0:3, ["bill_depth_mm", "body_mass_g"]]

   bill_depth_mm  body_mass_g
0           18.7       3750.0
1           17.4       3800.0
2           18.0       3250.0

In [84]:
df[df["species"] == "Gentoo"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
152,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,female,2007
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
154,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,female,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
...,...,...,...,...,...,...,...,...
270,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,female,2009
272,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [101]:
df.loc[:, ["species", "year"]]

       species  year
0       Adelie  2007
1       Adelie  2007
2       Adelie  2007
4       Adelie  2007
5       Adelie  2007
..         ...   ...
339  Chinstrap  2009
340  Chinstrap  2009
341  Chinstrap  2009
342  Chinstrap  2009
343  Chinstrap  2009

[333 rows x 2 columns]